---
url:        http://example.com
tries:      '2,10,50,100,500'
timeout:    1
work_dir:   /tmp/test_simple_http_monitor
ops_email:  ops@example.com
from_email: monitor@example.com
smtp_host:  smtp.example.com
smtp_user:  test
smtp_paswd: secret
